Refactored pgbdr job after code review with Dr Nic.

diff --git a/jobs/pgbdr/templates/bin/pgbdr b/jobs/pgbdr/templates/bin/pgbdr
--- a/jobs/pgbdr/templates/bin/pgbdr
+++ b/jobs/pgbdr/templates/bin/pgbdr
@@ -1,17 +1,40 @@
 #!/var/vcap/packages/bash-4.3/bin/bash
 
+# TODO: Investigate what monit_debugger was providing that we can't emit here
 source "$(dirname $(dirname ${0}))/shell/env"
 
-trap graceful_stop SIGTERM # Handle term signal sent by control script stop action.
+action=$1 ; shift
 
-initialize_database
+case ${action} in 
+  (start)
+    if ! [[ -d ${databasePath}/base ]]
+    then # Initialize the database if it has not already been initialized
+      rm -rf ${databasePath} # Clean up any previously failed attempts.
+      user chown ${jobStorePath}
+      pushd ${jobStorePath}
+      HOME=${jobStorePath} chpst -u ${userName}:${groupName} \"
+      ${pgbdrPkgPath}/bin/initdb -E UTF8 --local "en_US.UTF-8" -D ${databasePath}
+      popd
+    fi
 
-configure_pgbdr
+    user chown ${jobStorePath}
 
-ulimit -v unlimited
+    ulimit -v unlimited
 
-cat ${storePath}/config/postgresql.conf > ${dataPath}/postgresql.conf
-cat ${storePath}/config/pg_hba.conf > ${dataPath}/pg_hba.conf
-chmod 0640 ${dataPath}/*.conf
+    cat ${jobPath}/config/postgresql.conf > ${databasePath}/postgresql.conf
+    cat ${jobPath}/config/pg_hba.conf > ${databasePath}/pg_hba.conf
+    user chown ${jobStorePath}
+    chmod 0640 ${databasePath}/*.conf
 
-user exec ${binary} start ${binaryArgs[@]} -t 300
+    user exec ${pgbdrPkgPath}/bin/pg_ctl start -D ${databasePath} -s -t 300
+    ;;
+  (stop)
+    user run ${pgbdrPkgPath}/bin/pg_ctl stop -D ${databasePath} -m fast
+    rm -f ${pidFile}
+    exit 0 # Normal exit, return code 0
+    ;;
+  (*)
+    fail "usage: $0 <start|stop>"
+    ;;
+esac
+
